- name: Ansible Create user functionlity module demo
  hosts: host 
  become: yes
  become_method: sudo
  tasks:
    - name: Add the user with a primary group of sudo
      ansible.builtin.user:
        name: user
        password: "{{ 'password' | password_hash('sha512') }}"
        shell: /bin/bash
        group: sudo
        createhome: yes 
        home: /home/user

    - name: create folder .ssh
      file:
        path: /home/user/.ssh
        state: directory

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ./files/user.pub
        dest: /home/user/.ssh/id_rsa.pub 
        owner: user
        group: sudo
        mode: '0644'
